### ISSUE TITLE
Do any of the text in the multiple choice options need to be justified?

### ISSUE THREAD

**Issue by aarthyadityan** [inkdlab/writing-game-module-2#30]
In the intermediate, the correct body paragraph is justified

**Comment by loristokes** [comment]
No--that's only for intermediate.
Lori

Lori Stokes, Ph.D
FITW Development
College of Professional Studies




On Sat, Jan 14, 2017 at 11:45 PM -0500, "aarthyadityan" <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #30<https://github.com/inkdlab/writing-game-module-2/issues/30> to @loristokes<https://github.com/loristokes>.
